// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW3rcPfnRa--AyonjzUkrdO615y2zNZVk',
    appId: '1:1040962154792:web:2e4d98cad59a781a2ce01d',
    messagingSenderId: '1040962154792',
    projectId: 'omarks4',
    authDomain: 'omarks4.firebaseapp.com',
    databaseURL: 'https://omarks4.firebaseio.com',
    storageBucket: 'omarks4.appspot.com',
    measurementId: 'G-ET8CTLBN45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeQlExl6G2iE0_uxjWuYTC1WStu5NL2N8',
    appId: '1:1040962154792:android:4b78adc6359b53f52ce01d',
    messagingSenderId: '1040962154792',
    projectId: 'omarks4',
    databaseURL: 'https://omarks4.firebaseio.com',
    storageBucket: 'omarks4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3yEeTeLnNuRuZKk4S0sXlk7arbm2Iv8I',
    appId: '1:1040962154792:ios:ef6bb79ec07544152ce01d',
    messagingSenderId: '1040962154792',
    projectId: 'omarks4',
    databaseURL: 'https://omarks4.firebaseio.com',
    storageBucket: 'omarks4.appspot.com',
    iosClientId: '1040962154792-0sh6kbevu6t2kb6qlqsm72nmnhdf1soj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocFlutterBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3yEeTeLnNuRuZKk4S0sXlk7arbm2Iv8I',
    appId: '1:1040962154792:ios:ef6bb79ec07544152ce01d',
    messagingSenderId: '1040962154792',
    projectId: 'omarks4',
    databaseURL: 'https://omarks4.firebaseio.com',
    storageBucket: 'omarks4.appspot.com',
    iosClientId: '1040962154792-0sh6kbevu6t2kb6qlqsm72nmnhdf1soj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocFlutterBloc',
  );
}
